### DISCUSSION TITLE
Color for Axis

### DISCUSSION THREAD

**Discussion by stil4m** [gampleman/elm-visualization#13] [Q&A] [answered]
Would it make sense to add a stroke/text color field in the options record for Axis?

I'm currently using the axis, but the color is always `#000`.
To change it I have to reimplement it from scratch, and only change a few variables.
If it doesn't make sense, it is ok. But just wanted to check it.

**Comment by gampleman** [comment, marked as answer]
You can use CSS to change these visual properties:

```css
.domain { stroke: green; }
.tick line { stroke: green; }
.tick text { fill: green; }
```

will turn your axis green. You can use this technique to tune other things like the font or font size, or if you want to hide the tick marks for example.
