### ISSUE TITLE
Axis ticks color

### ISSUE THREAD

**Issue by jjagielka** [gampleman/elm-visualization#65]
There's a D3 axis trick to set the hight with a negative value to obtain a grid.
We can use that trick here as well, but the lines a drawn with `stroke "#000"` resulting in black lines.

A quick improvement would be to change the stroke value to `"currentColor"`.

Ref: https://css-tricks.com/currentcolor/

**Comment by megapctr** [comment]
It's possible to override the color with css
```scss
    .chart_axisGrid .tick > line {
      stroke: $grey-lighter;
    }
```
